# Generated by Django 2.0.4 on 2019-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
