# Generated by Django 2.0.4 on 2019-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0003_game_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.TextField()),
                ('all_players_played', models.BooleanField(default='False')),
                ('game_over', models.BooleanField(default='True')),
                ('players', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hit', models.BooleanField(default='False')),
                ('hand', models.TextField()),
                ('count', models.IntegerField(default='0')),
                ('room', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='hit',
            field=models.BooleanField(default='False'),
        ),
    ]
